name: Build and Push Docker Image

on:
  workflow_call:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            --build-arg PRIVATE_KEY=${{ secrets.PRIVATE_KEY }} \
            --build-arg SEPOLIA_RPC_URL=${{ secrets.SEPOLIA_RPC_URL }} \
            --build-arg CONTRACT_ADDRESS=${{ secrets.CONTRACT_ADDRESS }} \
            -t ghcr.io/${{ github.repository_owner }}/blockchain-api:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/blockchain-api:latest
