name: Blockchain Service CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml

  docker-publish:
    needs: unit-tests
    if: github.ref == 'refs/heads/master'
    uses: ./.github/workflows/docker-publish.yml
    secrets:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
      CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
    permissions:
      contents: read
      packages: write